name: stu_buddy
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  iconsax:
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  firebase_storage: ^13.0.0
  cloud_firestore: ^6.0.0
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.2.1
  get: ^4.7.2
  intl: ^0.20.2
  http: ^1.4.0
 
  logger: ^2.6.0
  lottie: ^3.3.1
  carousel_slider: ^5.1.1
  google_fonts:
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  syncfusion_flutter_charts: ^30.1.41
  getwidget: ^6.0.0
  sizer: ^3.0.5
  table_calendar: ^3.2.0
  image_picker: ^1.1.2
  firebase_app_check: ^0.4.0
  flutter_launcher_icons: ^0.14.4
  

 
  # url_launcher: ^6.2.5




dev_dependencies:
flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/logo_White.png"
  flutter_test:
    sdk: flutter




  flutter_lints: ^5.0.0

flutter:

  
  uses-material-design: true

 
  assets:
      - assets/logos/
      - assets/icons/
      - assets/images/onbo/
      - assets/images/FreCard/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf 
          weight: 300

        - asset: assets/fonts/Poppins-Regular.ttf 
          weight: 400

        - asset: assets/fonts/Poppins-Italic.ttf 
          weight: 400
          style: italic

        - asset: assets/fonts/Poppins-Medium.ttf 
          weight: 500

        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/Poppins-SemiBold.ttf 
          weight: 600

        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf 
          weight: 600
          style: italic

        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800






  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

